[tool.poetry]
name = "civ-weave"
version = "0.1.0"
description = ""
authors = ["James McNeill <james.mcneill@conjura.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
kuzu = "^0.0.7"
pydantic = "^2.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
ruff = "^0.0.287"
black = "^23.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
